#cloud-config 

package_update: true 
package_upgrade: true
bootcmd:
 - sysctl -w vm.max_map_count=524288
 - sysctl -w fs.file-max=131072
 - ulimit -n 131072 
 - ulimit -u 8192 
runcmd: 
 - cd /run/
 - git clone https://github.com/Kvaara/NGINX-RP-for-containers-cloudinit.git
 - cd ./NGINX-RP-for-containers-cloudinit
 - chmod +x init-letsencrypt.sh
 - [ bash, ./init-letsencrypt.sh ] # ./init-letsencrypt.sh (DOES NOT WORK BECAUSE OF NO PRIVILEGES? DUNNO WHY)
 - docker compose up