#cloud-config 

package_update: true 
package_upgrade: true
bootcmd:
 - sysctl -w vm.max_map_count=524288
 - sysctl -w fs.file-max=131072
 - ulimit -n 131072 
 - ulimit -u 8192 
runcmd: 
#  - mkdir /run/docker_compose/ 
 - cd /run/
 - git clone https://github.com/Kvaara/NGINX-RP-for-containers-cloudinit.git
 - cd ./NGINX-RP-for-containers-cloudinit
 - docker compose up -d